apiVersion: batch/v1
kind: CronJob
metadata:
  name: enrich-cronjob
  namespace: default # O el namespace que uses con ArgoCD
  labels:
    app: enrich
spec:
  schedule: "*/5 * * * *" # O tu horario deseado
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: enrich
            image: carlosmoreno7/enrich:latest
            imagePullPolicy: Always
          restartPolicy: OnFailure
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1